# Generated by Django 3.1.1 on 2020-09-30 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('body', models.CharField(max_length=1000, verbose_name='Summary')),
                ('author', models.CharField(max_length=100, verbose_name='Summary')),
                ('anime_title', models.IntegerField(choices=[(1, 'One Piece'), (2, 'Naruto'), (3, 'Bleach'), (4, 'My Hero Academia'), (5, 'Seven Deadly Sin'), (6, 'Others...')], verbose_name='Anime')),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000, verbose_name='Summary')),
                ('author', models.CharField(max_length=100, verbose_name='Summary')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('blog_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joseph_blog.blog', verbose_name='Blog Title')),
            ],
        ),
    ]
