# Generated by Django 3.1.1 on 2020-10-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joseph_blog', '0003_auto_20201001_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='datetime',
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.CharField(max_length=1000, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=1000, verbose_name='Body'),
        ),
    ]
