# Generated by Django 3.1.1 on 2020-10-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joseph_blog', '0004_auto_20201002_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog_title',
            field=models.IntegerField(verbose_name='Blog Title'),
        ),
    ]
