# Generated by Django 3.1.1 on 2020-10-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joseph_blog', '0005_auto_20201002_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog_title',
            field=models.CharField(max_length=100, verbose_name='Blog Title'),
        ),
    ]
